apiVersion: v1
kind: Service
metadata:
  name: shadowxlab-service
  namespace: shadowxlab
spec:
  type: NodePort
  selector:
    app: shadowxlab
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
